#!/usr/bin/bash

counter=0
while read line; do
  counter=$((counter+1))
  lesson="lesson-${counter}.tex"
  lesson_line="\input{${counter}{${current_date}}{${line}}{Unit 6}"

  # Output info to each file
  # echo ${lesson_line} >> ${lesson}
  # echo "" >> ${lesson}
  # echo "" >> ${lesson}
  # echo "" >> ${lesson}
  # echo "\newpage" >> ${lesson}

  # Clear all files
  true > ${lesson}
done <lessons
