code_dir: /home/hashem/Documents/school-notes/current-course
editor: nvim
viewer: zathura
terminal: xfce4-terminal
notes_dir: /home/hashem/Documents/school-notes
root: /home/hashem/Documents/school-notes/College/Year-1/semester-2
current_course: /home/hashem/Documents/school-notes/current-course
source_lessons_location: /home/hashem/Documents/school-notes/current-course/source-lectures.tex
projects_dir: /home/hashem/Documents/school-notes/projects
assignments_dir: /home/hashem/Documents/school-notes/current-course/assignments
assignments_folder: /home/hashem/Documents/school-notes/current-course/assignments/latex-files
unit_info_name: unit-info.tex
new_chap: False
home: /home/hashem
user: hashem
LESSON_RANGE_NUMBER: 1000

rofi_options:
  - -lines
  - 5
  - -markup-rows
  - -kb-row-down
  - Down
  - -kb-custom-1
  - Ctrl+n

tex_types:
  - .tex
  - .latex

discourage_folders:
  - images
  - assignments
  - figures
  - projects
  - .git
  - media
  - current-course
